apiVersion: v1
kind: ConfigMap
metadata:
  name: quack-config
  namespace: quack
data:
  audit.yaml: |
    # Log all requests at the Metadata level.
    apiVersion: audit.k8s.io/v1beta1
    kind: Policy
    rules:
    - level: Metadata
