apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quack
  namespace: quack
  labels:
    app: quack
spec:
  replicas: 1
  template:
    metadata:
      name: quack
      labels:
        app: quack
    spec:
      serviceAccountName: quack
      containers:
        - name: quack
          image: quack
          imagePullPolicy: Always
          args:
            - --tls-cert-file=/etc/certs/cert.pem
            - --tls-private-key-file=/etc/certs/key.pem
          volumeMounts:
          - name: certs
            mountPath: /etc/certs
            readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: quack-certs
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        "node-role.kubernetes.io/master": "true"
