apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: quack
webhooks:
  - name: quack.pusher.com
    clientConfig:
      service:
        name: quack
        namespace: quack
        path: /apis/quack.pusher.com/v1alpha1/admissionreviews
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources:
          - configmaps
        # - persistentvolumeclaims
          - daemonsets
          - deployments
        # - replicasets
          - statefulsets
        # - horizontalpodautoscalers
        # - cronjobs
        # - jobs
          - secrets
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: quack
        operator: NotIn
        values:
        - "false"
