apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: quack
webhooks:
  - name: quack.pusher.com
    clientConfig:
      service:
        name: quack
        namespace: quack
        path: /apis/quack.pusher.com/v1alpha1/admissionreviews
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources:
          - configmaps
          - daemonsets
          - deployments
          - statefulsets
          - ingresses
          - services
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: quack.pusher.com/enabled
        operator: In
        values:
        - "true"
