apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quack
  namespace: quack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quack
subjects:
- kind: ServiceAccount
  name: quack
  namespace: quack
